### ISSUE TITLE
[Dashboard] AWS 80 port elevated  privileges error

### ISSUE THREAD

**Issue by Phantom05** [Phantom05/Dashboard#11]
## 증상
+ pm2 restart는 잘됨, 
+ 서버도 잘돌아감 [http://13.209.73.163](http://13.209.73.163)
+ pm2 monit 나 pm2 log를 볼시 80번포트 권한 문제로 에러가남.  
+ aws에서 80번포트를 열어 줬는데도 권한 문제로 에러로되서 확인이 필요함..

## 스크린샷
> log 이미지
![23525235](https://user-images.githubusercontent.com/33567964/53931782-0015fd00-40da-11e9-9e03-2834a1d405cc.png)

> pm2 restart 0 시 이미지
![235235235](https://user-images.githubusercontent.com/33567964/53931901-80d4f900-40da-11e9-9d58-98c084c67123.png)

> pm2 list 이미지
![2623623623](https://user-images.githubusercontent.com/33567964/53932050-1c666980-40db-11e9-9a66-88c4bd69e118.png)

## 원인
+ 찾는중

## 시도
+  sudo pm2 restart 0 -> sudo 권한으로 pm2 실행

## 실행 환경
+ AWS ES2
## 포트 권한 이미지
![23523623623](https://user-images.githubusercontent.com/33567964/53931864-5edb7680-40da-11e9-8492-3d21209daec5.png)

<kdb>OS</kdb>
+ Window

<kdb>Browser</kdb>
+ Chrome

**Comment by chldbwnstm** [comment]
$ sudo apt-get install authbind
$ sudo touch /etc/authbind/byport/80
$ sudo chown yourusername /etc/authbind/byport/80
$ sudo chmod 755 /etc/authbind/byport/80
$ authbind --deep pm2 update

후 

sudo authbind --deep pm2

시도해보시길..!

**Comment by Phantom05** [comment]
잘안되여 인스턴스 재생성 후 정상 동작 확인.
